site_name: The BCI Project

theme:
  name: readthedocs

markdown_extensions:
  - toc:
      baselevel: 1

plugins:
  - search

nav:
  - Home:
    - index.md
    - Libraries:
        - bci-ue-logger-lib/docs/index.md
